import { expect, test } from "bun:test";
import { Namer } from "./namer";

test("namer works", () => {
  const namer = new Namer("abc");
  expect(namer.newId()).toBe("a");
  expect(namer.newId()).toBe("b");
  expect(namer.newId()).toBe("c");
  expect(namer.newId()).toBe("aa");
  expect(namer.newId()).toBe("ab");
  expect(namer.newId()).toBe("ac");
  expect(namer.newId()).toBe("ba");
  expect(namer.newId()).toBe("bb");
  expect(namer.newId()).toBe("bc");
  expect(namer.newId()).toBe("ca");
  expect(namer.newId()).toBe("cb");
  expect(namer.newId()).toBe("cc");
  expect(namer.newId()).toBe("aaa");
  expect(namer.newId()).toBe("aab");
  expect(namer.newId()).toBe("aac");
  expect(namer.newId()).toBe("aba");
  expect(namer.newId()).toBe("abb");
  expect(namer.newId()).toBe("abc");
  expect(namer.newId()).toBe("aca");
  expect(namer.newId()).toBe("acb");
  expect(namer.newId()).toBe("acc");
  expect(namer.newId()).toBe("baa");
  expect(namer.newId()).toBe("bab");
  expect(namer.newId()).toBe("bac");
  expect(namer.newId()).toBe("bba");
  expect(namer.newId()).toBe("bbb");
  expect(namer.newId()).toBe("bbc");
  expect(namer.newId()).toBe("bca");
  expect(namer.newId()).toBe("bcb");
  expect(namer.newId()).toBe("bcc");
  expect(namer.newId()).toBe("caa");
  expect(namer.newId()).toBe("cab");
  expect(namer.newId()).toBe("cac");
  expect(namer.newId()).toBe("cba");
  expect(namer.newId()).toBe("cbb");
  expect(namer.newId()).toBe("cbc");
  expect(namer.newId()).toBe("cca");
  expect(namer.newId()).toBe("ccb");
  expect(namer.newId()).toBe("ccc");
  expect(namer.newId()).toBe("aaaa");
});
